/* Plugin generated by AMXX-Studio */

#include "amxmodx.inc"
#include "missions_api.inc"

#define PLUGIN "Mission #1 - Test"
#define VERSION "1.0"
#define AUTHOR "MJ"

// natives - precache - init - cfg

new g_iMissionID;

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR);
	
	
}

public fwd_LoadMissions() 
{
	cmd_CreateMission("Unbelievable Winner","You need to win the game","Wins",mTYPE_EXPERT, 5);
	cmd_AddMissionLevel(2,600,255500);
	g_iMissionID = cmd_AddMission();
}

public fwd_PlayerWon(const iIndex)
{
	if(g_iMissionID == mission_GetUserMissionID(iIndex))
		mission_UpdateUserData(iIndex);
}
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ ansicpg1252\\ deff0{\\ fonttbl{\\ f0\\ fnil\\ fcharset0 Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1037\\ f0\\ fs16 \n\\ par }
*/
